### ISSUE TITLE
The project is not ready yet?

### ISSUE THREAD

**Issue by Wintreist** [antico94/RushRoyaleBot_v4#3]
hi, is this a working version? I ran into several problems during the installation, and only then noticed that there are no config.ini files and bot.py... The project is not ready yet?
Please check, requirements.txt , `pywin32~=305` in this case is not installed, `pywin32==305` is fixed; As I understood, when installing `PyAutoGUI==0.9.52` he pulls up `PyMsgBox-1.0.9` which crashes during installation, `pip uninstall typing` is fixed

**Comment by antico94** [comment]
Hi, I've abandoned this project. But I can recommend you a working version that i found on GitHub.
https://github.com/AxelBjork/Rush-Royale-Bot
Hope this will be useful to you.

Kind regards,
Anticod

**Comment by Wintreist** [comment]
Got it, thanks.
